export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_ERROR = "REGISTER_STUDENT_ERROR";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";

export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_ERROR = "GET_STUDENT_ERROR";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";

export const EDIT_STUDENT_REQUEST = "EDIT_STUDENT_REQUEST";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
