export const REGISTER_TUTOR_REQUEST = "REGISTER_TUTOR_REQUEST";
export const REGISTER_TUTOR_ERROR = "REGISTER_TUTOR_ERROR";
export const REGISTER_TUTOR_SUCCESS = "REGISTER_TUTOR_SUCCESS";

export const GET_TUTOR_REQUEST = "GET_TUTOR_REQUEST";
export const GET_TUTOR_ERROR = "GET_TUTOR_ERROR";
export const GET_TUTOR_SUCCESS = "GET_TUTOR_SUCCESS";

export const DELETE_TUTOR_REQUEST = "DELETE_TUTOR_REQUEST";
export const DELETE_TUTOR_ERROR = "DELETE_TUTOR_ERROR";
export const DELETE_TUTOR_SUCCESS = "DELETE_TUTOR_SUCCESS";

export const EDIT_TUTOR_REQUEST = "EDIT_TUTOR_REQUEST";
export const EDIT_TUTOR_ERROR = "EDIT_TUTOR_ERROR";
export const EDIT_TUTOR_SUCCESS = "EDIT_TUTOR_SUCCESS";
