export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST";
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";

export const LOGIN_TUTOR_SUCCESS = "LOGIN_TUTOR_SUCCESS";
export const LOGIN_TUTOR_ERROR = "LOGIN_TUTOR_ERROR";
export const LOGIN_TUTOR_REQUEST = "LOGIN_TUTOR_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
