export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";

export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_ERROR = "GET_ADMIN_ERROR";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";

export const DELETE_ADMIN_REQUEST = "DELETE_ADMIN_REQUEST";
export const DELETE_ADMIN_ERROR = "DELETE_ADMIN_ERROR";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
