export const CREATE_CONTENT_REQUEST = "CREATE_CONTENT_REQUEST";
export const CREATE_CONTENT_ERROR = "CREATE_CONTENT_ERROR";
export const CREATE_CONTENT_SUCCESS = "CREATE_CONTENT_SUCCESS";

export const GET_CONTENT_REQUEST = "GET_CONTENT_REQUEST";
export const GET_CONTENT_ERROR = "GET_CONTENT_ERROR";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";

export const GET_SINGLE_CONTENT_REQUEST = "GET_SINGLE_CONTENT_REQUEST";
export const GET_SINGLE_CONTENT_ERROR = "GET_SINGLE_CONTENT_ERROR";
export const GET_SINGLE_CONTENT_SUCCESS = "GET_SINGLE_CONTENT_SUCCESS";

export const DELETE_CONTENT_REQUEST = "DELETE_CONTENT_REQUEST";
export const DELETE_CONTENT_ERROR = "DELETE_CONTENT_ERROR";
export const DELETE_CONTENT_SUCCESS = "DELETE_CONTENT_SUCCESS";
