export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_ERROR = "CREATE_QUIZ_ERROR";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";

export const GET_QUIZ_REQUEST = "GET_QUIZ_REQUEST";
export const GET_QUIZ_ERROR = "GET_QUIZ_ERROR";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";

export const DELETE_QUIZ_REQUEST = "DELETE_QUIZ_REQUEST";
export const DELETE_QUIZ_ERROR = "DELETE_QUIZ_ERROR";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";

