export const CREATE_DOUBT_REQUEST = "CREATE_DOUBT_REQUEST";
export const CREATE_DOUBT_ERROR = "CREATE_DOUBT_ERROR";
export const CREATE_DOUBT_SUCCESS = "CREATE_DOUBT_SUCCESS";

export const GET_DOUBT_REQUEST = "GET_DOUBT_REQUEST";
export const GET_DOUBT_ERROR = "GET_DOUBT_ERROR";
export const GET_DOUBT_SUCCESS = "GET_DOUBT_SUCCESS";

export const GET_SINGLE_DOUBT_REQUEST = "GET_SINGLE_DOUBT_REQUEST";
export const GET_SINGLE_DOUBT_ERROR = "GET_SINGLE_DOUBT_ERROR";
export const GET_SINGLE_DOUBT_SUCCESS = "GET_SINGLE_DOUBT_SUCCESS";

export const DELETE_DOUBT_REQUEST = "DELETE_DOUBT_REQUEST";
export const DELETE_DOUBT_ERROR = "DELETE_DOUBT_ERROR";
export const DELETE_DOUBT_SUCCESS = "DELETE_DOUBT_SUCCESS";

export const RESOLVE_DOUBT_REQUEST = "RESOLVE_DOUBT_REQUEST";
export const RESOLVE_DOUBT_ERROR = "RESOLVE_DOUBT_ERROR";
export const RESOLVE_DOUBT_SUCCESS = "RESOLVE_DOUBT_SUCCESS";

export const ADD_DOUBT_RESPONSE_REQUEST = "ADD_DOUBT_RESPONSE_REQUEST";
export const ADD_DOUBT_RESPONSE_ERROR = "ADD_DOUBT_RESPONSE_ERROR";
export const ADD_DOUBT_RESPONSE_SUCCESS = "ADD_DOUBT_RESPONSE_SUCCESS";
